shared_literature.bib
=> Add starting bib file for shared literature

git_cheat_sheet.txt
filled git cheat sheet with most used commands
=> Feature/fill cheat sheet#13

Cheatsheet_MD.md
Added Cheatsheet for Markdown.
Would be great if everyone could use it to directly typeset correctly into our Etherpad! Would make the documentation much easier!
=> feature/cheatsheet_md add Cheatsheet for Markdown v1.0 #18

Cheatsheet_MD.md
Added H6
Added missing Image explanation
Minor fixes #19 #18
=> Cleaned up and Minor fixes

protokolle/2020-04-22_htw-pv3_software-session.md
I copied protocol-3 from main to subfolder protokolle and renamed it. The protocol was edited by @khelfen
=> add protocol 3 #11

PV_EFH_Literaturlinks.txt
=> Transform literature list into markdown and expand it - #20

protokolle/2020-04-15_htw-pv3_daten.md
I created a new branch after messed up the old one. This includes protocol 2 transcribed to markdown syntax.
- Originally started by @Ludee. 
- I did some markdown corrections
=> add protocol 2 #11

Codes_GitBash_So_Far.md
This is a Review of the Code and explanation of the command lines used in GitBash so far. From the configuration and setup up to date. Hope it helps to get used to the new Workflow.
=> GitBash_Code_So_Far_#10

shared_literature_PV_FE.bib
I found a neet little online tool for calculationg basic pv system data. It's called PVSol online and is basically the little brother of the feature packed program PVSol premium.
If you are thinking about producing your own enery and don't really know how to get started or what aspects are important I found an overview for those people who are interested in building their own system.
=> add literature #45

protokolle/2020-05-06_htw-pv3_postgresql_II.md, protokolle/2020-06-06_htw-pv3_postgresql_II.md
Added protocol from 2020-05-06.
Please review and confirm. #43
=> Adding Protocol 2020-05-06 (#43)

SQL/SQL.md
I have added some basic SQL-commands with a link to a Sql-training. I create also a folder to organize files that belongs to SQL and PostgreSQL. Please Review!
=> Adding_SQL-commands_#50

git_literature.md
expand git_literature.md --> add git tutorials
=> add git tutorials -#48

SQL/PostGis_Enabling.md
here is the code for Enabling the extension PostGis on PostgreSQL. Please Review it!
=> Adding_Postgis_Enabling_Code

crib-cheat_git.md
Zeilenanfang deswegen "going" zu "Going" verändert.
=> Line 39 going to Going changed. Issue #97.

crib-cheat_git.md
I changed the closed bracket in line 30 to a comma.
=> line 30 - change ")" to "," - #96

.gitignore, crib-cheat_postgres.md
I corrected the layout of the Postgres.md. Can someone check it
=> Feature 100 postges 

crib-cheat_git.md
Added successfully, waiting for review to merge :)
=> New Git Command added #101

CONTRIBUTING.md
Added some lines to the section 4 of CONTRIBUTING.md
Close #131
=> Updated CONTRIBUTING.md in section 4 #131

README.md
Added a short decription to README about the literature repositiory
Close #127
=> Feature 127 complement README

README.md
Added a short decription for git to README.md #133
=> Added short description for git #133

CONTRIBUTING.md
just a short correction of a grammatical case
=> Grammatical correction of CONTRIBUTING.md file #146

CONTRIBUTING.md, README.md, crib-cheat_git.md, crib-cheat_markdown.md, crib-cheat_postgres.md, crib-cheat_python.md, references.bib
Feel free to merge. Thanks in advance.
=> Feature 150 typo markdownmd

crib-cheat_git.md
I have changed the spelling of Comiting into Comitting. Please have a look and review it.
=> Spelling of Comiting has been changed into Comitting #155

crib-cheat_git.md
I have added a new video tutorial for `crib-cheat_git.md`. Can you please have a look and review it?
=> Feature 167 add new video tutorial

crib-cheat_git.md
The structure of the document `crib-cheat_git.md` should be now more organized. Request to merge with the `dev` branch. Awaiting for review.
=> Done restructuring the file `crib-cheat_git.md` #165

README.md
=> Add a comment #173

references.bib
Reverts htw-pv3/literature#182
=> Revert "added meld to references.bib #181"

references.bib
added software meld to the bibtex-file references.bib after reverting the merge.
=> Adding "Meld" to references.bib #181

crib-cheat_python.md
=> Fixed grammar and spelling in crib-cheat_python

crib-cheat_git.md
not complete at all but enough for the task :)
=> corrected tense crib cheat git

README.md
I'm done with my changes. Please check and give me a short feedback. 
Close #178
=> Updated the description of the README file #178

references.bib
Changed Date & Version of JabRef entry in 'references.bib'
=> Feature 218 jabref

references.bib
Abschnitt hat gefehlt. Wird hier hinzugefügt.
=> miniconda Abschnitt hinzugefügt #221

references.bib
=> url change #211

references.bib
Please approve this pull request!:)
=> Change QGIS Title #213

references.bib
my first pull request - PostgreSQL Version updated from 13.2 to 17.4
=>  PostgreSQL Version updated from 13.2 to 17.4 #223

crib-cheat_git.md
Lösung dokumentieren
Closes #260
=> Add an empty row #260
